//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    
    public partial class sp_GetDistance_Business_Result13
    {
        public Nullable<long> SNO { get; set; }
        public long Id { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<long> SubCategoryId { get; set; }
        public string BusinessName { get; set; }
        public Nullable<long> SelectedCity { get; set; }
        public Nullable<long> Subscription { get; set; }
        public string MESSAGE { get; set; }
        public string ContactPerson { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsApprovedByAdmin { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public double Distance { get; set; }
        public string CategoryName { get; set; }
        public string UserMessage { get; set; }
        public string ButtonTitle { get; set; }
        public string SubCategoryName { get; set; }
        public string CityName { get; set; }
        public string Image { get; set; }
        public string PremiumImage { get; set; }
        public long UserId { get; set; }
    }
}
