//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BusinessBooking
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<long> BusinessId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsApprovedByAdmin { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public string Time { get; set; }
        public string Message { get; set; }
    
        public virtual tbl_Login tbl_Login { get; set; }
        public virtual tbl_Business tbl_Business { get; set; }
    }
}
